### PR TITLE
Fix missing flag for nodejs

### PR DESCRIPTION
**Pull request by rmbaad**

### CODE REVIEW

**Comment by ai** [comment]
Do we need it for Node 12-13?

**Comment by rmbaad** [comment]
I think yes, because I got this error on nodejs 12 and nodejs 13 (via nvm). This fast fix was help me

**Comment by ai** [comment]
Very strange. Are you sure that you do not use Node.js 10?

I tested it with Node.js 13 and CI runs it with Node.js 12.

**Comment by rmbaad** [comment]
It's my fail, I checked it before node version change. But why you don't let to run it on nodejs 10? :)

**Comment by ai** [comment]
Yeap, we also need fix for Node.js 10. I just wanted to be sure that I didn't miss anything important for Node.js 12.

**Comment by ai** [comment]
@rmbaad can you try GitHub version in Node.js 10?

```
yarn remove check-dts
yarn add --dev check-dts@ai/check-dts
npx check-dts
```

I am not sure that `npx` will use this comment.

**Comment by rmbaad** [comment]
Thank you!

**Comment by rmbaad** [comment]
No :( it's not working for npx. I'm going to think how to fix it

**Comment by ai** [comment]
I added Node.js 10 support ea57e86

**Comment by ai** [comment]
Released at 0.1.2

**Pull request merged**
